// Mocks generated by Mockito 5.x from annotations
// in drivevault/test/features/vehicles/vehicle_repository_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:drivevault/core/network/api_client.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

/// A class which mocks [ApiClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockApiClient extends _i1.Mock implements _i2.ApiClient {
  MockApiClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<Map<String, dynamic>> get(String? path) =>
      (super.noSuchMethod(
        Invocation.method(#get, [path]),
        returnValue: _i3.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
        returnValueForMissingStub:
            _i3.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i3.Future<Map<String, dynamic>>);

  @override
  _i3.Future<Map<String, dynamic>> patch(
    String? path, {
    required Map<String, dynamic>? body,
  }) =>
      (super.noSuchMethod(
        Invocation.method(#patch, [path], {#body: body}),
        returnValue: _i3.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
        returnValueForMissingStub:
            _i3.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i3.Future<Map<String, dynamic>>);

  @override
  _i3.Future<Map<String, dynamic>> post(
    String? path, {
    required Map<String, dynamic>? body,
  }) =>
      (super.noSuchMethod(
        Invocation.method(#post, [path], {#body: body}),
        returnValue: _i3.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
        returnValueForMissingStub:
            _i3.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i3.Future<Map<String, dynamic>>);

  @override
  _i3.Future<List<Map<String, dynamic>>> postAndExpectList(
    String? path, {
    required Map<String, dynamic>? body,
  }) =>
      (super.noSuchMethod(
        Invocation.method(#postAndExpectList, [path], {#body: body}),
        returnValue: _i3.Future<List<Map<String, dynamic>>>.value(
          <Map<String, dynamic>>[],
        ),
        returnValueForMissingStub: _i3.Future<List<Map<String, dynamic>>>.value(
          <Map<String, dynamic>>[],
        ),
      ) as _i3.Future<List<Map<String, dynamic>>>);

  @override
  _i3.Future<List<Map<String, dynamic>>> getList(
    String? path, {
    Map<String, dynamic>? queryParams,
  }) =>
      (super.noSuchMethod(
        Invocation.method(#getList, [path], {#queryParams: queryParams}),
        returnValue: _i3.Future<List<Map<String, dynamic>>>.value(
          <Map<String, dynamic>>[],
        ),
        returnValueForMissingStub: _i3.Future<List<Map<String, dynamic>>>.value(
          <Map<String, dynamic>>[],
        ),
      ) as _i3.Future<List<Map<String, dynamic>>>);

  @override
  _i3.Future<void> delete(String? path) =>
      (super.noSuchMethod(
        Invocation.method(#delete, [path]),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}
