// Mocks generated by Mockito 5.4.6 from annotations
// in drivevault/test/features/vehicles/vehicles_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:drivevault/features/vehicles/data/vehicle_repository.dart'
    as _i3;
import 'package:drivevault/features/vehicles/domain/vehicle.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeVehicle_0 extends _i1.SmartFake implements _i2.Vehicle {
  _FakeVehicle_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [VehicleRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockVehicleRepository extends _i1.Mock implements _i3.VehicleRepository {
  MockVehicleRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Vehicle> fetchVehicle(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#fetchVehicle, [id]),
            returnValue: _i4.Future<_i2.Vehicle>.value(
              _FakeVehicle_0(this, Invocation.method(#fetchVehicle, [id])),
            ),
          )
          as _i4.Future<_i2.Vehicle>);

  @override
  _i4.Future<List<_i2.Vehicle>> fetchVehicles() =>
      (super.noSuchMethod(
            Invocation.method(#fetchVehicles, []),
            returnValue: _i4.Future<List<_i2.Vehicle>>.value(<_i2.Vehicle>[]),
          )
          as _i4.Future<List<_i2.Vehicle>>);

  @override
  _i4.Future<_i2.Vehicle> createVehicle(Map<String, dynamic>? data) =>
      (super.noSuchMethod(
            Invocation.method(#createVehicle, [data]),
            returnValue: _i4.Future<_i2.Vehicle>.value(
              _FakeVehicle_0(this, Invocation.method(#createVehicle, [data])),
            ),
          )
          as _i4.Future<_i2.Vehicle>);

  @override
  _i4.Future<_i2.Vehicle> updateVehicle(
    String? id,
    Map<String, dynamic>? data,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateVehicle, [id, data]),
            returnValue: _i4.Future<_i2.Vehicle>.value(
              _FakeVehicle_0(
                this,
                Invocation.method(#updateVehicle, [id, data]),
              ),
            ),
          )
          as _i4.Future<_i2.Vehicle>);

  @override
  _i4.Future<void> deleteVehicle(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteVehicle, [id]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}
