// Mocks generated by Mockito 5.x from annotations
// in drivevault/test/features/vehicles/vehicles_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:drivevault/features/vehicles/data/vehicle_repository.dart'
    as _i2;
import 'package:drivevault/features/vehicles/domain/vehicle.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;

/// A class which mocks [VehicleRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockVehicleRepository extends _i1.Mock implements _i2.VehicleRepository {
  MockVehicleRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.Vehicle>> fetchVehicles() =>
      (super.noSuchMethod(
        Invocation.method(#fetchVehicles, []),
        returnValue:
            _i3.Future<List<_i4.Vehicle>>.value(<_i4.Vehicle>[]),
        returnValueForMissingStub:
            _i3.Future<List<_i4.Vehicle>>.value(<_i4.Vehicle>[]),
      ) as _i3.Future<List<_i4.Vehicle>>);

  @override
  _i3.Future<_i4.Vehicle> createVehicle(Map<String, dynamic>? data) =>
      (super.noSuchMethod(
        Invocation.method(#createVehicle, [data]),
        returnValue: _i3.Future<_i4.Vehicle>.value(
          _FakeVehicle(),
        ),
        returnValueForMissingStub: _i3.Future<_i4.Vehicle>.value(
          _FakeVehicle(),
        ),
      ) as _i3.Future<_i4.Vehicle>);

  @override
  _i3.Future<_i4.Vehicle> updateVehicle(
    String? id,
    Map<String, dynamic>? data,
  ) =>
      (super.noSuchMethod(
        Invocation.method(#updateVehicle, [id, data]),
        returnValue: _i3.Future<_i4.Vehicle>.value(
          _FakeVehicle(),
        ),
        returnValueForMissingStub: _i3.Future<_i4.Vehicle>.value(
          _FakeVehicle(),
        ),
      ) as _i3.Future<_i4.Vehicle>);

  @override
  _i3.Future<void> deleteVehicle(String? id) =>
      (super.noSuchMethod(
        Invocation.method(#deleteVehicle, [id]),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}

class _FakeVehicle extends _i1.SmartFake implements _i4.Vehicle {
  _FakeVehicle() : super(_FakeVehicle, Invocation.method(#_FakeVehicle, []));
}
